### ISSUE TITLE
memory allocation of 134217728 bytes failed

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-worker#21]
After Block 565362, the worker fails to allocate the memory needed in order to backup the state and continue synching with the chain. The memory to be allocated is suspiciously little above 128MB

```
Aug 19 13:17:24 devsgx03 encointer-worker[17152]: [2020-08-19T11:17:24Z DEBUG substratee_worker_enclave] Scanning block 565362 for relevant xt                                                                                                       
Aug 19 13:17:24 devsgx03 encointer-worker[17152]: [2020-08-19T11:17:24Z DEBUG substratee_worker_enclave] Restored ECC pubkey:                                                                                                                        
Aug 19 13:17:24 devsgx03 encointer-worker[17152]: [2020-08-19T11:17:24Z DEBUG substratee_worker_enclave::io::light_validation] backup chain relay state
Aug 19 13:17:25 devsgx03 encointer-worker[17152]: [2020-08-19T11:17:25Z DEBUG substratee_worker_enclave::io::light_validation] Seal Chain Relay State. Current state: LightValidationTest { num_relays: 1, tracked_relays: {1: RelayInfo { last_final
ized_block_header_number: 565362, current_validator_set: [(<wasm:stripped>, 1), (<wasm:stripped>, 1)], current_validator_set_id: 0 amount of transaction in tx_inclusion_queue: 70 }} }
Aug 19 13:17:27 devsgx03 encointer-worker[17152]: memory allocation of 134217728 bytes failed
```

On disk, the `chain_relay_db.bin` file  is 102MB. The state shards are very small, as expected:

```
~/encointer-worker-as-service/bin/shards$ du -h
12K     ./3LjCHdiNbNLKEtwGtBf6qHGZnfKFyjLu9v3uxVgDL35C
40K     ./7eLSZLSMShw4ju9GvuMmoVgeZxZimtvsGTSvLEdvcRqQ
56K     .
``` 
The `7eL...` shard is "sea of crete"

We probably should split the chain relay file into parts of i.e. 32MB?

**Comment by brenzi** [comment]
the enclave.config says
```
  <StackMaxSize>0x40000</StackMaxSize>
  <HeapMaxSize>0x20000000</HeapMaxSize>
```
So heap should be 512MB, stack 256kB. However, SGX does have a documented limitation at 128MB (with paging up to 4GB, but we're allocating a contiguous memory block....).

**Comment by brenzi** [comment]
@clangenb's fix #22 saves about a factor of 8. 1M blocks cause 32MB of chain_raly_db size (and take 24h to sync: #23 )
that's ok for now, but we may re-visit this issue around April 2021. 

we should think about why we need to store block hashes at all. Probably we could just store the headers back to the last finalized and worker-synched block

**Comment by clangenb** [comment]
I believe storing the hashes (previously the headers) was simply inspired by generic light client design, where storing headers to a certain extend is needed in case no finalization is provided. Is my thinking correct?

I currently see no reason to store the hashes

**Comment by brenzi** [comment]
closing for now
