### ISSUE TITLE
Solve OnCeremonyPhaseChange and per-block storage updates

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-worker#3]
The encointer_scheduler pallet is instanciated onchain and it maintains the ceremony state machine.
For testnet Gesell, the encointer_ceremonies pallet gets invoked with `OnCeremonyPhaseChange` and performs `assign()` `issue()` or `purge` upon state changes. There are no extrinsics involved, the trigger is a state change.

So far, SubstraTEE has no trigger on state change. We could implement the following:

We could update pre-defined on-chain storage (`EncointerScheduler::CurrentPhase`) for every block, even if no extrinsics are included. Upon state change, we call the function [on_ceremony_phase_change](https://github.com/encointer/pallets/blob/f60169a908675bb90ae54cfa8b9000fc08ca45e7/ceremonies/src/lib.rs#L595)

The following storage is either needed for TrustedGetter or for functions invoked by `on_ceremony_phase_change`. These should also be updated every block

* `EncointerScheduler::CurrentCeremonyIndex`
* `EncointerScheduler::NextPhaseTimestamp`
* `EncointerScheduler::PhaseDurations`
* `EncointerCurrencies::CurrencyIdentifiers`
* `EncointerCurrencies::Bootstrappers`
* `EncointerCurrencies::Locations`

There might be more generic solutions, but this should work

**Comment by clangenb** [comment]
The state update upon block import leaves one problem. The worker does currently not know which shards are assigned to him. I believe that the most straight forward way to go about this is a third state that is persisted.

```
struct EnclaveState {
     assigned_shards: Vec<ShardIdentifier>
}
```

what do you think and would we need additional fields to keep track of?
