### ISSUE TITLE
deploy testnet Cantillon worker on devsgx03

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-worker#4]
SGX in HW debug mode
WSS exposed for worker-api

run on devsgx03 as system service with autorestart
* 1 worker (ensure that RA has no SGX warnings. Report status should be `OK`)
* 1 full node for worker to do RPC with

**Comment by electronix** [comment]
### WSS reverse proxy
Certificate from Let's Encrypt installed.
Configuration of nginx done:
- External port 443 -> internal port 19944
- External ports 9940-9950 -> internal ports 19940-19950

### System service
Configuration for Gesell node done as systemd service on substratee03.scs.ch. Cantillon would follow the same scheme.

### SGX Remote Attestation
Report status `OK` is not feasible as we cannot update the BIOS to a newer version. Currently, the status is (`CONFIGURATION_AND_SW_HARDENING_NEEDED`).

## Missing
- Cantillon worker
- System service for Cantillon node
